# This is a basic workflow to help you get started with Actions 

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - labeled

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # syntax:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       py_version: ["3.8"]
  #       distro: ["alpine"]
  #   env:
  #     UID: "1001"
  #     PY_VERSION: ${{ matrix.py_version }}
  #     DISTRO: ${{ matrix.distro }}
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     # Runs a set of commands using the runners shell
  #     - name: Run syntax tests
  #       run: |
  #         pip install flake8
  #         flake8 calculator --count --select=E9,F63,F7,F82 --show-source --statistics
  CI:
    # The type of runner that the job will run on
    if: github.event_name == 'push' || github.event.label.name == 'runtest'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: ["3.8", "3.7", "3.6"]
        distro: ["alpine", "debian"]
    env:
      UID: "1001"
      PY_VERSION: ${{ matrix.py_version }}
      DISTRO: ${{ matrix.distro }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run syntax tests
        run: |
          docker-compose run app flake8 calculator --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run primary tests
        run: |
          docker-compose up --build --exit-code-from app
      - name: Run style tests
        run: |
          docker-compose run app flake8 --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E722,F401,W605 calculator --count --max-complexity=62 --max-line-length=127 --statistics
  # style:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       py_version: ["3.8"]
  #       distro: ["alpine"]
  #   env:
  #     UID: "1001"
  #     PY_VERSION: ${{ matrix.py_version }}
  #     DISTRO: ${{ matrix.distro }}
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v2

  #     # Runs a set of commands using the runners shell
  #     - name: Run styling tests
  #       run: |
  #         pip install flake8
  #         flake8 --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E722,F401,W605 datajoint \
  #           --count --max-complexity=62 --max-line-length=127 --statistics
